spring.application.name=SpringBoot-Automation-Production

# Enable .env file
spring.config.import=optional:file:.env[.properties]

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# default 200
server.tomcat.threads.max=200
server.port=${HTTP_PORT}

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.ldap.enabled=false

# Profile
spring.profiles.active=@spring.profiles.active@

################################################################
############################# Hibernate ########################
# Hibernate
spring.jpa.properties.hibernate.show_sql=false

# HTTP PUT, PATCH, DELETE
sping.mvc.hiddenmethod.filter.enabled=true

################################################################
############################# LDAP ########################

ldap.url=${LDAP_URL}
ldap.domain=${LDAP_DOMAIN}

################################################################
######################## JWT ###################################

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-minutes=10
jwt.refresh-token-expiration-days=30

