SELECT * FROM BD_USR;
SELECT * FROM BD_PLAN;




create table BD_USR(
                       F_ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       USERNAME varchar(100) NOT NULL ,
                       PASSWORD varchar NOT NULL
);

create table BD_PLAN(
                       ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       PLAN_ID varchar(100) NOT NULL ,
                       DATA varchar NOT NULL
);

